---
name: Super-Linter          
on: push

permissions:
  contents: read
  checks: write
  statuses: write
  pull-requests: write

jobs:
  super-lint:              
    name: Lint code base    
    runs-on: ubuntu-latest  
    steps:
      - name: Checkout code 
        uses: actions/checkout@v3

      - name: Run Super-Linter      
        uses: github/super-linter@v6
        env:                         
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
